[package]
name = "devutils"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
smalloc = { path = "../smalloc", package = "smmalloc" }
wyhash = "0.6.0"
wyrand = "0.3.2"
