[package]
name = "hellosmalloc"
version.workspace = true
edition.workspace = true

[dependencies]
smalloc = { path = "../smalloc" }
ctor = "0.2"

[[bin]]
name = "hellosmalloc_procmacro"

[[bin]]
name = "hellosmalloc_ctor"
