[package]
name = "smalloc"
version.workspace = true
edition.workspace = true

[dependencies]
plat = { path = "../plat" }
smalloc-macros = { path = "../smalloc-macros" }

[dev-dependencies]
devutils = { path = "../devutils" }
